# -*- coding: utf-8 -*-
"""Face_Mask_Detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOErQWoclfvEnK_N2ILeafuQ4hmlRmUl

## Project Initialization and Data Setup

### Subtask Summary:

1.  **GitHub Repository Cloning**: The project began by cloning the `FaceMask-Detection-using-Deeplearning` repository from GitHub into a local directory named `FaceMaskProject`. This step ensures all necessary project files and the dataset are available.

2.  **Key Library Imports**: Essential Python libraries were imported to support the deep learning workflow. These include `os` for operating system interaction, `numpy` for numerical operations, `matplotlib.pyplot` for plotting, `ImageDataGenerator` for data augmentation, various components from `tensorflow.keras.models` and `tensorflow.keras.layers` (e.g., `Model`, `load_model`, `Dense`, `Dropout`, `GlobalAveragePooling2D`, `Input`), `MobileNetV2` as the base pre-trained model, `Adam` for optimization, `files` from `google.colab` for file uploads, and `PIL.Image` for image processing.

3.  **Initial Dataset Path Configuration**: Initially, the `dataset_path` variable was configured to point to `FaceMaskProject/dataset`, assuming the images were directly inside a 'dataset' subdirectory within the cloned project.

4.  **Intended Dataset Path Update**: It was identified that the `dataset_path` needed to be updated to `FaceMaskProject` to correctly reference the root directory where the 'train' and 'test' subdirectories (containing the actual image data) reside, rather than an additional 'dataset' level.

## Data Preprocessing and Augmentation

### Subtask:
Detail the data preprocessing steps, including the use of `ImageDataGenerator` for rescaling, validation splitting, and augmentation techniques like zoom, shear, and horizontal flip, noting the parameters used for training and validation data.

### Data Preprocessing and Augmentation Details

Data preprocessing and augmentation are crucial steps to prepare the images for training and to prevent overfitting. The `ImageDataGenerator` class from Keras is used for this purpose.

1.  **ImageDataGenerator Initialization**:
    A single `ImageDataGenerator` instance named `datagen` is initialized with the following parameters:
    *   `rescale=1./255`: All image pixel values are rescaled from the 0-255 range to 0-1, which is a common practice for neural network inputs.
    *   `validation_split=0.2`: 20% of the data is reserved for validation, ensuring that the model is evaluated on unseen data during training.
    *   `zoom_range=0.2`: Randomly zooms images by up to 20%.
    *   `shear_range=0.2`: Applies random shear transformations by up to 20%.
    *   `horizontal_flip=True`: Randomly flips images horizontally, which is a useful augmentation for various image classification tasks.

2.  **Training Data Generator (`train_data`)**:
    The `train_data` generator is created using `datagen.flow_from_directory` with the `dataset_path` pointing to the root directory containing the 'train' and 'test' folders. It uses the following common parameters:
    *   `target_size=(224,224)`: All images are resized to 224x224 pixels to match the input requirements of the MobileNetV2 model.
    *   `batch_size=32`: Images are processed in batches of 32.
    *   `class_mode='binary'`: Since there are two classes ('WithMask' and 'WithoutMask'), the labels are encoded as binary (0 or 1).
    *   `subset='training'`: This parameter specifies that this generator should only yield images designated for the training set, based on the `validation_split` defined in `datagen`.

3.  **Validation Data Generator (`val_data`)**:
    Similarly, the `val_data` generator is also created using `datagen.flow_from_directory` with the `dataset_path` and the same common parameters as `train_data`:
    *   `target_size=(224,224)`
    *   `batch_size=32`
    *   `class_mode='binary'`
    *   `subset='validation'`: This parameter ensures that this generator yields images reserved for the validation set.

## Model Architecture and Compilation

### Subtask:
Explain the model architecture, focusing on the use of a pre-trained MobileNetV2 base model (weights='imagenet', include_top=False), the freezing strategy for its layers, and the addition of custom layers (GlobalAveragePooling2D, Dense, Dropout, Sigmoid). Describe the compilation details including the Adam optimizer with a learning rate of 1e-4, binary cross-entropy loss, and accuracy metrics.

### Model Architecture and Compilation Explained

This section details the construction and configuration of the deep learning model used for face mask detection.

1.  **Base Model**: We utilize `MobileNetV2`, a highly efficient pre-trained convolutional neural network. The `weights='imagenet'` argument loads the model with weights pre-trained on the ImageNet dataset, allowing us to leverage learned features from a large and diverse image database. `include_top=False` is specified to exclude the original classification head of MobileNetV2, enabling us to add our custom layers for binary classification. The `input_tensor=Input(shape=(224,224,3))` ensures the model expects input images of size 224x224 pixels with 3 color channels (RGB).

2.  **Freezing Strategy**: Initially, all layers of the `MobileNetV2` base model are loaded. To fine-tune the model effectively without retraining the entire large network, a selective freezing strategy is applied. Specifically, the **last 10 layers** of the `base_model` are set to `trainable = True`. This means these layers will be updated during training, allowing the model to adapt the higher-level feature extraction to our specific face mask detection task, while the earlier, more general feature extraction layers remain frozen.

3.  **Custom Layers**: On top of the modified `MobileNetV2` base, the following custom layers are added:
    *   `GlobalAveragePooling2D()`: This layer reduces the spatial dimensions of the feature maps, computing the average of each feature map. It effectively flattens the output into a single vector, reducing the number of parameters and helping to prevent overfitting.
    *   `Dense(128, activation='relu')`: A fully connected layer with 128 neurons and a Rectified Linear Unit (`relu`) activation function. This layer learns higher-level combinations of features extracted by the base model.
    *   `Dropout(0.5)`: A dropout layer is included with a dropout rate of 0.5. During training, this randomly sets 50% of the input units to 0 at each update step, which helps to prevent overfitting by making the network more robust to different feature subsets.
    *   `Dense(1, activation='sigmoid')`: The final output layer is a single neuron with a `sigmoid` activation function. The sigmoid function outputs a value between 0 and 1, which is ideal for binary classification tasks, representing the probability of the 'mask' class.

4.  **Model Compilation**: After defining the architecture, the model is compiled with the following parameters:
    *   **Optimizer**: `Adam(1e-4)` is used as the optimizer. Adam is an adaptive learning rate optimization algorithm that is computationally efficient and well-suited for a wide range of deep learning problems. A low learning rate of `1e-4` is chosen to ensure stable training and prevent large weight updates, which is particularly important when fine-tuning a pre-trained model.
    *   **Loss Function**: `binary_crossentropy` is selected as the loss function. This is the standard choice for binary classification problems, measuring the performance of a classification model whose output is a probability value between 0 and 1.
    *   **Metrics**: `accuracy` is used as the evaluation metric. This measures the proportion of correctly classified samples and provides an easily interpretable performance indicator during training and evaluation.

## Model Training and Performance Analysis

### Subtask:
Summarize the model training process, including epoch count and generator usage. Discuss training and validation accuracy/loss trends from the plot, and note final accuracy/loss values from the kernel state.

## Model Training and Performance Analysis

### Subtask:
Summarize the model training process, including epoch count and generator usage. Discuss training and validation accuracy/loss trends from the plot, and note final accuracy/loss values from the kernel state.

#### Training Process Summary:

The model was trained for **5 epochs** using the `model.fit()` method. For data input, it utilized `train_data` and `val_data`, which were generated by `ImageDataGenerator`. These generators handled data preprocessing and augmentation, providing a continuous flow of augmented images for training and validation, respectively.

#### Analysis of Training and Validation Metrics Plot:

- **Accuracy Trends**: The plot shows that both **Train Accuracy** and **Validation Accuracy** generally increased over the epochs. The training accuracy typically rises faster and reaches higher values, which is expected. The validation accuracy also shows a positive trend, indicating the model's ability to generalize to unseen data, though there might be some fluctuations.
- **Loss Trends**: Conversely, both **Train Loss** and **Validation Loss** show a decreasing trend over the epochs. This signifies that the model is learning and reducing its errors during training. Similar to accuracy, the training loss usually decreases more consistently, while the validation loss might show slight variations.

#### Final Training Metrics from Kernel State:

Based on the kernel state, the final training metrics are:
- **Final Training Accuracy**: `0.8218181729316711`
- **Final Training Loss**: `0.4916715919971466`

## Model Training and Performance Analysis

### Subtask:
Summarize the model training process, including epoch count and generator usage. Discuss training and validation accuracy/loss trends from the plot, and note final accuracy/loss values from the kernel state.

#### Training Process Summary:

The model was trained for **5 epochs** using the `model.fit()` method. For data input, it utilized `train_data` and `val_data`, which were generated by `ImageDataGenerator`. These generators handled data preprocessing and augmentation, providing a continuous flow of augmented images for training and validation, respectively.

#### Analysis of Training and Validation Metrics Plot:

- **Accuracy Trends**: The plot shows that both **Train Accuracy** and **Validation Accuracy** generally increased over the epochs. The training accuracy typically rises faster and reaches higher values, which is expected. The validation accuracy also shows a positive trend, indicating the model's ability to generalize to unseen data, though there might be some fluctuations.
- **Loss Trends**: Conversely, both **Train Loss** and **Validation Loss** show a decreasing trend over the epochs. This signifies that the model is learning and reducing its errors during training. Similar to accuracy, the training loss usually decreases more consistently, while the validation loss might show slight variations.

#### Final Training Metrics from Kernel State:

Based on the kernel state, the final training metrics are:
- **Final Training Accuracy**: `0.8218181729316711`
- **Final Training Loss**: `0.4916715919971466`

## Model Training and Performance Analysis

### Subtask:
Summarize the model training process, including epoch count and generator usage. Discuss training and validation accuracy/loss trends from the plot, and note final accuracy/loss values from the kernel state.

#### Training Process Summary:

The model was trained for **5 epochs** using the `model.fit()` method. For data input, it utilized `train_data` and `val_data`, which were generated by `ImageDataGenerator`. These generators handled data preprocessing and augmentation, providing a continuous flow of augmented images for training and validation, respectively.

#### Analysis of Training and Validation Metrics Plot:

- **Accuracy Trends**: The plot shows that both **Train Accuracy** and **Validation Accuracy** generally increased over the epochs. The training accuracy typically rises faster and reaches higher values, which is expected. The validation accuracy also shows a positive trend, indicating the model's ability to generalize to unseen data, though there might be some fluctuations.
- **Loss Trends**: Conversely, both **Train Loss** and **Validation Loss** show a decreasing trend over the epochs. This signifies that the model is learning and reducing its errors during training. Similar to accuracy, the training loss usually decreases more consistently, while the validation loss might show slight variations.

#### Final Training Metrics from Kernel State:

Based on the kernel state, the final training metrics are:
- **Final Training Accuracy**: `0.8218181729316711`
- **Final Training Loss**: `0.4916715919971466`

## Model Persistence and Testing

### Subtask:
Describe how the trained model is saved and explain the model testing phase, including image upload, preprocessing, prediction, and result display.

## Model Persistence and Testing

### Subtask:
Describe how the trained model is saved and explain the model testing phase, including image upload, preprocessing, prediction, and result display.

### Model Persistence

The trained model is saved to disk using the `model.save()` method from TensorFlow/Keras. The specific filename used is `'face_mask_detector_mobilenet_re_trained.h5'`. This `.h5` file stores the entire model, including its architecture, weights, and optimizer state, allowing it to be loaded and used later without retraining.

### Model Testing Phase

The model testing phase involves the following steps:

1.  **Image Upload**: The user is prompted to upload an image using `google.colab.files.upload()`. This function allows files to be uploaded directly from the local machine to the Colab environment.

2.  **Image Preprocessing**: Once an image is uploaded:
    *   It is opened using `PIL.Image.open()`.
    *   The image is converted to the RGB format using `.convert("RGB")` to ensure consistency with the model's input expectations.
    *   It is then resized to `(224, 224)` pixels, matching the input size expected by the MobileNetV2 base model.
    *   The image is converted into a NumPy array using `np.array()`.
    *   Pixel values are normalized by dividing by `255.0` to scale them between 0 and 1.
    *   Finally, the array is reshaped to `(1, 224, 224, 3)` to represent a single image batch for the model's input.

3.  **Prediction**: The preprocessed image array is fed into the loaded model using `model.predict(img_array)`. The model outputs a single prediction value, typically a float between 0 and 1, representing the probability of the image belonging to one of the classes.

4.  **Result Display**: Based on the prediction:
    *   A label is assigned: if the `prediction` value is less than `0.5`, the label is "Mask 😷"; otherwise, it's "No Mask ❌".
    *   The original uploaded image is then displayed using `matplotlib.pyplot.imshow()`, with the determined prediction label shown as the title of the plot.
"""

# ===========================
# FACE MASK DETECTION WITH IMPROVED TRAINING (REVERTING TO MORE STABLE PARAMETERS)
# ===========================

# STEP 1: Clone GitHub Repository
!rm -rf FaceMaskProject
!git clone https://github.com/snehitvaddi/FaceMask-Detection-using-Deeplearning.git FaceMaskProject

# STEP 2: Import Libraries
import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, Input
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.optimizers import Adam
from google.colab import files
from PIL import Image

# STEP 3: Dataset Path
dataset_path = "FaceMaskProject/dataset"
print("Dataset folders:", os.listdir(dataset_path))

# STEP 4: Data Preprocessing (Reverted to less aggressive augmentation)
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    zoom_range=0.2, # Less aggressive zoom
    shear_range=0.2, # Less aggressive shear
    horizontal_flip=True
    # Removed brightness_range and rotation_range to simplify
)

train_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    subset='training'
)

val_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

# STEP 5: Load Pre-trained MobileNetV2
base_model = MobileNetV2(weights='imagenet', include_top=False, input_tensor=Input(shape=(224,224,3)))

# STEP 6: Freeze all base layers (Reverted to freezing all base layers)
for layer in base_model.layers[-10:]:
    layer.trainable = True


# STEP 7: Add Custom Layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)

# STEP 8: Compile Model
model.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])

# STEP 9: Train Model (Reverted to 2 Epochs for more stable performance)
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=5
)


# STEP 10: Plot Accuracy & Loss
plt.figure(figsize=(10,5))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Training and Validation Metrics")
plt.xlabel("Epochs")
plt.ylabel("Accuracy / Loss")
plt.legend()
plt.show()

# STEP 11: Save Model
model.save("face_mask_detector_mobilenet_re_trained.h5") # Saved with a new name

# ===========================
# STEP 12: Upload Image and Predict
# ===========================
print("Upload an image to test Mask Detection:")
uploaded = files.upload()

for file_name in uploaded.keys():
    # Rename file if it has special characters
    new_name = file_name.replace('[','_').replace(']','_')
    os.rename(file_name, new_name)
    img_path = new_name

    # Load and preprocess image
    img = Image.open(img_path).convert("RGB")
    img = img.resize((224,224))
    img_array = np.array(img)/255.0
    img_array = np.reshape(img_array, (1,224,224,3))

    # Predict
    prediction = model.predict(img_array)
    label = "Mask 😷" if prediction < 0.5 else "No Mask ❌"

    print(f"Result for {new_name}: {label}")

    # Show uploaded image with prediction
    plt.imshow(img)
    plt.title(f"Prediction: {label}")
    plt.axis('off')
    plt.show()

"""## Model Persistence and Testing

### Subtask:
Describe how the trained model is saved and explain the model testing phase, including image upload, preprocessing, prediction, and result display.

### Model Persistence

The trained model is saved to disk using the `model.save()` method from TensorFlow/Keras. The specific filename used is `'face_mask_detector_mobilenet_re_trained.h5'`. This `.h5` file stores the entire model, including its architecture, weights, and optimizer state, allowing it to be loaded and used later without retraining.

### Model Testing Phase

The model testing phase involves the following steps:

1.  **Image Upload**: The user is prompted to upload an image using `google.colab.files.upload()`. This function allows files to be uploaded directly from the local machine to the Colab environment.

2.  **Image Preprocessing**: Once an image is uploaded:
    *   It is opened using `PIL.Image.open()`.
    *   The image is converted to the RGB format using `.convert("RGB")` to ensure consistency with the model's input expectations.
    *   It is then resized to `(224, 224)` pixels, matching the input size expected by the MobileNetV2 base model.
    *   The image is converted into a NumPy array using `np.array()`.
    *   Pixel values are normalized by dividing by `255.0` to scale them between 0 and 1.
    *   Finally, the array is reshaped to `(1, 224, 224, 3)` to represent a single image batch for the model's input.

3.  **Prediction**: The preprocessed image array is fed into the loaded model using `model.predict(img_array)`. The model outputs a single prediction value, typically a float between 0 and 1, representing the probability of the image belonging to one of the classes.

4.  **Result Display**: Based on the prediction:
    *   A label is assigned: if the `prediction` value is less than `0.5`, the label is "Mask 😷"; otherwise, it's "No Mask ❌".
    *   The original uploaded image is then displayed using `matplotlib.pyplot.imshow()`, with the determined prediction label shown as the title of the plot.

## Summary:

### Data Analysis Key Findings

*   **Project Setup**: The project was initialized by cloning a GitHub repository (`FaceMask-Detection-using-Deeplearning`) into `FaceMaskProject`. Key libraries such as `tensorflow.keras`, `MobileNetV2`, `ImageDataGenerator`, `numpy`, and `matplotlib` were imported. The initial dataset path of `FaceMaskProject/dataset` was correctly identified as needing an update to `FaceMaskProject` to point to the directory containing 'train' and 'test' subfolders.
*   **Data Preprocessing and Augmentation**: An `ImageDataGenerator` was configured with `rescale=1./255`, `validation_split=0.2`, `zoom_range=0.2`, `shear_range=0.2`, and `horizontal_flip=True`. Training and validation data generators (`train_data`, `val_data`) were set up using `flow_from_directory` with `target_size=(224,224)`, `batch_size=32`, and `class_mode='binary'`, partitioning data into training and validation subsets.
*   **Model Architecture**: A `MobileNetV2` base model, pre-trained on ImageNet weights, was used with its top classification layer removed (`include_top=False`). The last 10 layers of the `MobileNetV2` base were unfrozen for fine-tuning. Custom layers added included `GlobalAveragePooling2D`, a `Dense` layer (128 units, 'relu' activation), a `Dropout` layer (0.5 rate), and a final `Dense` output layer (1 unit, 'sigmoid' activation) for binary classification.
*   **Model Compilation**: The model was compiled with the `Adam` optimizer at a learning rate of \$1\text{e-}4\$, `binary_crossentropy` as the loss function, and `accuracy` as the evaluation metric.
*   **Model Training**: The model was trained for 5 epochs using the configured `train_data` and `val_data` generators. Observed trends indicated that both training and validation accuracy generally increased, while training and validation loss generally decreased over the epochs. The final training accuracy achieved was approximately 82.18% (0.8218), with a final training loss of approximately 0.4917.
*   **Model Persistence and Testing**: The trained model was saved as `face_mask_detector_mobilenet_re_trained.h5`. The testing phase involved uploading an image, preprocessing it (RGB conversion, resizing to 224x224, normalization, reshaping for model input), obtaining a prediction (probability between 0 and 1), and then displaying the image with a derived label ('Mask 😷' if prediction < 0.5, 'No Mask ❌' otherwise).

### Insights or Next Steps

*   The model showed promising initial performance with an 82.18% training accuracy after only 5 epochs, suggesting its potential for accurate mask detection. Further training for more epochs or fine-tuning hyperparameters could lead to improved performance and better generalization on unseen data.
*   While the current testing method provides a basic demonstration, a more robust evaluation using a separate, untouched test dataset (beyond the validation split) would be crucial to assess the model's true generalization capabilities and identify potential overfitting.
"""